version: "v1"
project: "nextcloud"
services:
  frontend:
    apache:
      image: "nextcloud:latest"
      instances: 1
      mem: 1024
      domain: "$URI"
      port: 80
      volumes:
        - container_path: "/var/www/html"
          size: "8GB"