version: "v1"
project: "wekan"
services:
  frontend:
    meteor:
      image: "wekanteam/wekan:v4.53"
      instances: 1
      mem: 512
      domain: $URI
      port: 8080
      env:
        - MONGO_URL: "mongodb://mongodb.backend.wekan/wekan"
        - ROOT_URL: "https://$URI"
      dependencies:
        - "../backend/mongodb"
  backend:
    mongodb:
      image: "mongo:mongo:4.4.1-bionic"
      instances: 1
      mem: 512
      volumes:
        - path: "/data/db"
        - path: "/data/configdb"
      cmd: "mongod --smallfiles --oplogSize 128 --bind_ip_all"
